name: measures_gbxml

on: [workflow_call, workflow_dispatch]

env:
  GBXML: v1.2.0

jobs:
  update:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: dst


      - name: checkout NREL/gbxml-to-openstudio
        uses: actions/checkout@v4
        with:
          repository: NREL/gbxml-to-openstudio
          ref: ${{ env.GBXML }}
          path: src
          sparse-checkout: |
            measures/gbxml_import
            measures/gbxml_import_advanced
            measures/gbxml_import_hvac
            measures/gbxml_postprocess

      - name: copy files from NREL/gbxml-to-openstudio
        shell: bash
        run: |
          ls
          cp -r src/measures/gbxml_import/* dst/measures/gbxml_import/
          cp -r src/measures/gbxml_import_advanced/* dst/measures/gbxml_import_advanced/
          cp -r src/measures/gbxml_import_hvac/* dst/measures/gbxml_import_hvac/
          cp -r src/measures/gbxml_postprocess/* dst/measures/gbxml_postprocess/

      - name: upload files
        uses: actions/upload-artifact@v3
        with:
          name: measures
          path: dst/measures

  pull-request:
    needs: update
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3

      - name: list
        run: |
          ls measures/

      - name: pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update measures gbxml
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[action] update measures gbxml'
          branch: action/update-measures-gbxml
          base: main
