name: measures_gbxml

on: [workflow_call, workflow_dispatch]

env:
  GBXML: master

jobs:
  update:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: sparse checkout NREL/gbxml-to-openstudio
        uses: actions/checkout@v4
        with:
          repository: NREL/gbxml-to-openstudio
          ref: ${{ env.GBXML }}
          path: gbxml
          sparse-checkout: |
            measures/import_gbxml
            measures/advanced_import_gbxml
            measures/gbxml_hvac_import
            measures/gbxml_to_openstudio_cleanup

      - name: copy files from NREL/gbxml-to-openstudio
        shell: bash
        run: cp -r gbxml/measures measures && ls measures

      - name: upload files
        uses: actions/upload-artifact@v3
        with:
          name: measures
          path: measures

  pull-request:
    needs: update
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v3
      
      - name: list
        run: |
          ls measures/   

      - name: pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update measures gbxml
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[action] update measures gbxml'
          branch: action/update-measures-gbxml
          base: main 
